#!/usr/bin/env python3
"""
ALPHA OMEGA - NATURAL LANGUAGE SCRIPT GENERATION
AI-powered script creation and execution
Version: 2.0.0
"""

import asyncio
import json
import logging
import os
import subprocess
import tempfile
import time
import hashlib
from pathlib import Path
from typing import Dict, Any, List, Optional
from dataclasses import dataclass, field
from enum import Enum
import re


class ScriptLanguage(Enum):
    PYTHON = "python"
    BASH = "bash"
    POWERSHELL = "powershell"
    JAVASCRIPT = "javascript"
    BATCH = "batch"


class ScriptStatus(Enum):
    DRAFT = "draft"
    READY = "ready"
    RUNNING = "running"
    COMPLETED = "completed"
    FAILED = "failed"


@dataclass
class GeneratedScript:
    id: str
    name: str
    description: str
    language: ScriptLanguage
    code: str
    parameters: Dict[str, Any] = field(default_factory=dict)
    dependencies: List[str] = field(default_factory=list)
    status: ScriptStatus = ScriptStatus.DRAFT
    created_at: float = field(default_factory=time.time)
    updated_at: float = field(default_factory=time.time)
    last_run: float = 0
    run_count: int = 0
    success_count: int = 0
    output: str = ""
    error: str = ""

    def to_dict(self) -> Dict[str, Any]:
        return {
            "id": self.id,
            "name": self.name,
            "description": self.description,
            "language": self.language.value,
            "code": self.code,
            "parameters": self.parameters,
            "dependencies": self.dependencies,
            "status": self.status.value,
            "created_at": self.created_at,
            "updated_at": self.updated_at,
            "last_run": self.last_run,
            "run_count": self.run_count,
            "success_count": self.success_count,
        }


@dataclass
class ScriptResult:
    success: bool
    output: str
    error: str
    return_code: int
    duration_ms: float
    script_id: str


class ScriptGenerator:
    """AI-powered script generation"""

    def __init__(self, llm_provider=None):
        self.llm_provider = llm_provider
        self.logger = logging.getLogger("ScriptGenerator")

        self._templates = self._load_templates()

    def _load_templates(self) -> Dict[str, str]:
        """Load script templates"""
        return {
            "python": '''#!/usr/bin/env python3
"""
{description}
Generated by Alpha Omega
"""

import sys
import os
import json
import argparse
from pathlib import Path

def main():
    parser = argparse.ArgumentParser(description="{description}")
    {args}
    args = parser.parse_args()
    
    try:
{body}
    except Exception as e:
        print(f"Error: {{e}}", file=sys.stderr)
        sys.exit(1)

if __name__ == "__main__":
    main()
''',
            "bash": """#!/bin/bash
# {description}
# Generated by Alpha Omega

set -e

{body}
""",
            "powershell": """
# {description}
# Generated by Alpha Omega

param(
{params}
)

{body}
""",
            "javascript": """/**
 * {description}
 * Generated by Alpha Omega
 */

const {{ execSync }} = require('child_process');
const fs = require('fs');
const path = require('path');

async function main() {{
{body}
}}

main().catch(console.error);
""",
        }

    async def generate_script(
        self,
        description: str,
        language: ScriptLanguage = ScriptLanguage.PYTHON,
        parameters: Dict[str, Any] = None,
    ) -> GeneratedScript:
        """Generate a script from natural language description"""
        script_id = hashlib.md5(f"{description}{time.time()}".encode()).hexdigest()[:12]

        code = await self._generate_code(description, language, parameters)

        script = GeneratedScript(
            id=script_id,
            name=self._generate_name(description),
            description=description,
            language=language,
            code=code,
            parameters=parameters or {},
        )

        return script

    async def _generate_code(
        self,
        description: str,
        language: ScriptLanguage,
        parameters: Dict[str, Any] = None,
    ) -> str:
        """Generate code using LLM or templates"""
        if self.llm_provider:
            prompt = self._build_generation_prompt(description, language, parameters)
            response = await self.llm_provider.generate(prompt)
            if response.success:
                return self._extract_code(response.text, language)

        return self._generate_from_template(description, language, parameters)

    def _build_generation_prompt(
        self,
        description: str,
        language: ScriptLanguage,
        parameters: Dict[str, Any] = None,
    ) -> str:
        """Build prompt for LLM"""
        lang_name = language.value.capitalize()

        prompt = f"""Generate a {lang_name} script that: {description}

Requirements:
1. Include proper error handling
2. Add comments explaining the code
3. Make it production-ready
4. Include necessary imports/modules"""

        if parameters:
            prompt += f"\n5. Accept these parameters: {json.dumps(parameters)}"

        prompt += f"\n\nProvide only the {lang_name} code, wrapped in ```{language.value} code blocks."

        return prompt

    def _extract_code(self, text: str, language: ScriptLanguage) -> str:
        """Extract code from LLM response"""
        pattern = rf"```{language.value}\s*\n(.*?)```"
        match = re.search(pattern, text, re.DOTALL | re.IGNORECASE)

        if match:
            return match.group(1).strip()

        if "```" in text:
            parts = text.split("```")
            if len(parts) >= 2:
                return parts[1].strip()

        return text

    def _generate_from_template(
        self,
        description: str,
        language: ScriptLanguage,
        parameters: Dict[str, Any] = None,
    ) -> str:
        """Generate code from template"""
        template = self._templates.get(language.value, self._templates["python"])

        if language == ScriptLanguage.PYTHON:
            args_str = ""
            if parameters:
                for name, config in parameters.items():
                    args_str += f'parser.add_argument("--{name}", help="{config.get("help", "")}")\n    '

            body = "        # TODO: Implement script logic\n        pass"

            return template.format(
                description=description,
                args=args_str or "pass",
                body=body,
            )

        elif language == ScriptLanguage.BASH:
            body = f"# {description}\n# TODO: Implement script logic"
            return template.format(description=description, body=body)

        elif language == ScriptLanguage.POWERSHELL:
            params_str = ""
            if parameters:
                for name, config in parameters.items():
                    params_str += f"    [string]${name},\n"

            body = f"# {description}\n# TODO: Implement script logic"
            return template.format(
                description=description, params=params_str.rstrip(",\n"), body=body
            )

        return template.format(description=description, body="    // TODO: Implement")

    def _generate_name(self, description: str) -> str:
        """Generate script name from description"""
        words = description.lower().split()[:5]
        name = "_".join(w for w in words if w.isalnum())
        return f"script_{name}" if name else "generated_script"


class ScriptRunner:
    """Execute generated scripts"""

    def __init__(self, script_dir: str = "scripts"):
        self.script_dir = Path(script_dir)
        self.script_dir.mkdir(parents=True, exist_ok=True)
        self.logger = logging.getLogger("ScriptRunner")

    async def run_script(
        self,
        script: GeneratedScript,
        args: Dict[str, Any] = None,
        timeout: int = 60000,
    ) -> ScriptResult:
        """Run a generated script"""
        script_path = self.script_dir / f"{script.id}.{script.language.value}"

        with open(script_path, "w", encoding="utf-8") as f:
            f.write(script.code)

        if script.language != ScriptLanguage.PYTHON or os.name != "nt":
            os.chmod(script_path, 0o755)

        start_time = time.time()

        try:
            cmd = self._build_command(script, script_path, args)

            process = await asyncio.create_subprocess_exec(
                *cmd,
                stdout=asyncio.subprocess.PIPE,
                stderr=asyncio.subprocess.PIPE,
            )

            try:
                stdout, stderr = await asyncio.wait_for(
                    process.communicate(), timeout=timeout / 1000
                )
            except asyncio.TimeoutError:
                process.kill()
                return ScriptResult(
                    success=False,
                    output="",
                    error="Script timed out",
                    return_code=-1,
                    duration_ms=timeout,
                    script_id=script.id,
                )

            duration_ms = (time.time() - start_time) * 1000

            return ScriptResult(
                success=process.returncode == 0,
                output=stdout.decode("utf-8", errors="replace"),
                error=stderr.decode("utf-8", errors="replace"),
                return_code=process.returncode or 0,
                duration_ms=duration_ms,
                script_id=script.id,
            )

        except Exception as e:
            return ScriptResult(
                success=False,
                output="",
                error=str(e),
                return_code=-1,
                duration_ms=(time.time() - start_time) * 1000,
                script_id=script.id,
            )

    def _build_command(
        self,
        script: GeneratedScript,
        script_path: Path,
        args: Dict[str, Any] = None,
    ) -> List[str]:
        """Build command to execute script"""
        args = args or {}

        if script.language == ScriptLanguage.PYTHON:
            cmd = ["python", str(script_path)]
            for key, value in args.items():
                cmd.append(f"--{key}")
                cmd.append(str(value))

        elif script.language == ScriptLanguage.BASH:
            cmd = ["bash", str(script_path)]

        elif script.language == ScriptLanguage.POWERSHELL:
            cmd = [
                "powershell",
                "-ExecutionPolicy",
                "Bypass",
                "-File",
                str(script_path),
            ]

        elif script.language == ScriptLanguage.BATCH:
            cmd = ["cmd", "/c", str(script_path)]

        elif script.language == ScriptLanguage.JAVASCRIPT:
            cmd = ["node", str(script_path)]

        else:
            cmd = ["python", str(script_path)]

        return cmd


class ScriptLibrary:
    """Library of generated scripts"""

    def __init__(self, db_path: str = "data/scripts.db"):
        self.db_path = Path(db_path)
        self.db_path.parent.mkdir(parents=True, exist_ok=True)
        self.logger = logging.getLogger("ScriptLibrary")

        self._scripts: Dict[str, GeneratedScript] = {}
        self._init_db()

    def _init_db(self):
        """Initialize database"""
        import sqlite3

        with sqlite3.connect(self.db_path) as conn:
            conn.execute("""
                CREATE TABLE IF NOT EXISTS scripts (
                    id TEXT PRIMARY KEY,
                    name TEXT NOT NULL,
                    description TEXT,
                    language TEXT,
                    code TEXT,
                    parameters TEXT,
                    dependencies TEXT,
                    status TEXT,
                    created_at REAL,
                    updated_at REAL,
                    last_run REAL,
                    run_count INTEGER,
                    success_count INTEGER
                )
            """)
            conn.commit()

    def save_script(self, script: GeneratedScript):
        """Save script to library"""
        import sqlite3

        self._scripts[script.id] = script

        with sqlite3.connect(self.db_path) as conn:
            conn.execute(
                """
                INSERT OR REPLACE INTO scripts
                (id, name, description, language, code, parameters, dependencies, status, created_at, updated_at, last_run, run_count, success_count)
                VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
                """,
                (
                    script.id,
                    script.name,
                    script.description,
                    script.language.value,
                    script.code,
                    json.dumps(script.parameters),
                    json.dumps(script.dependencies),
                    script.status.value,
                    script.created_at,
                    script.updated_at,
                    script.last_run,
                    script.run_count,
                    script.success_count,
                ),
            )
            conn.commit()

    def get_script(self, script_id: str) -> Optional[GeneratedScript]:
        """Get script by ID"""
        if script_id in self._scripts:
            return self._scripts[script_id]

        import sqlite3

        with sqlite3.connect(self.db_path) as conn:
            cursor = conn.execute("SELECT * FROM scripts WHERE id = ?", (script_id,))
            row = cursor.fetchone()
            if row:
                return GeneratedScript(
                    id=row[0],
                    name=row[1],
                    description=row[2],
                    language=ScriptLanguage(row[3]),
                    code=row[4],
                    parameters=json.loads(row[5]) if row[5] else {},
                    dependencies=json.loads(row[6]) if row[6] else [],
                    status=ScriptStatus(row[7]),
                    created_at=row[8],
                    updated_at=row[9],
                    last_run=row[10],
                    run_count=row[11],
                    success_count=row[12],
                )
        return None

    def list_scripts(
        self,
        language: ScriptLanguage = None,
        status: ScriptStatus = None,
    ) -> List[GeneratedScript]:
        """List scripts"""
        scripts = list(self._scripts.values())

        if language:
            scripts = [s for s in scripts if s.language == language]
        if status:
            scripts = [s for s in scripts if s.status == status]

        return scripts

    def delete_script(self, script_id: str) -> bool:
        """Delete script"""
        if script_id in self._scripts:
            del self._scripts[script_id]

            import sqlite3

            with sqlite3.connect(self.db_path) as conn:
                conn.execute("DELETE FROM scripts WHERE id = ?", (script_id,))
                conn.commit()
            return True
        return False


class ScriptGenerationEngine:
    """Main script generation engine"""

    def __init__(self, llm_provider=None):
        self.generator = ScriptGenerator(llm_provider)
        self.runner = ScriptRunner()
        self.library = ScriptLibrary()
        self.logger = logging.getLogger("ScriptGenerationEngine")

    async def initialize(self) -> bool:
        """Initialize the engine"""
        self.logger.info("Script Generation Engine initialized")
        return True

    async def create_script(
        self,
        description: str,
        language: str = "python",
        parameters: Dict[str, Any] = None,
    ) -> GeneratedScript:
        """Create a new script from description"""
        lang = ScriptLanguage(language.lower())
        script = await self.generator.generate_script(description, lang, parameters)
        self.library.save_script(script)

        self.logger.info(f"Created script: {script.name}")
        return script

    async def run_script(
        self,
        script_id: str,
        args: Dict[str, Any] = None,
    ) -> ScriptResult:
        """Run a script by ID"""
        script = self.library.get_script(script_id)
        if not script:
            return ScriptResult(
                success=False,
                output="",
                error="Script not found",
                return_code=-1,
                duration_ms=0,
                script_id=script_id,
            )

        result = await self.runner.run_script(script, args)

        script.last_run = time.time()
        script.run_count += 1
        if result.success:
            script.success_count += 1
        self.library.save_script(script)

        return result

    async def create_and_run(
        self,
        description: str,
        language: str = "python",
        args: Dict[str, Any] = None,
    ) -> Tuple[GeneratedScript, ScriptResult]:
        """Create and immediately run a script"""
        script = await self.create_script(description, language)
        result = await self.run_script(script.id, args)
        return script, result

    async def debug_script(self, script_id: str) -> Dict[str, Any]:
        """Debug a script"""
        script = self.library.get_script(script_id)
        if not script:
            return {"error": "Script not found"}

        issues = []
        suggestions = []

        if not script.code.strip():
            issues.append("Script is empty")

        if script.language == ScriptLanguage.PYTHON:
            if "import " not in script.code and len(script.code) > 100:
                issues.append("No imports found - may need required modules")

            if "try:" not in script.code and "except" not in script.code:
                suggestions.append("Consider adding error handling")

        success_rate = script.success_count / max(script.run_count, 1)

        return {
            "script_id": script_id,
            "name": script.name,
            "issues": issues,
            "suggestions": suggestions,
            "success_rate": round(success_rate, 2),
            "run_count": script.run_count,
        }

    def get_stats(self) -> Dict[str, Any]:
        """Get engine statistics"""
        scripts = self.library.list_scripts()

        return {
            "total_scripts": len(scripts),
            "total_runs": sum(s.run_count for s in scripts),
            "total_successes": sum(s.success_count for s in scripts),
            "languages": {
                lang.value: sum(1 for s in scripts if s.language == lang)
                for lang in ScriptLanguage
            },
        }


from typing import Tuple
